spring:
  application:
    # 配置中心+注册中心
    name: SeirMeng-edcation
  datasource:
    url: jdbc:mysql://localhost:3306/seirmeng_haidong_edu?serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  # json的全局配置
  jackson:
    time-zone: GMT+8
    date-format: java.text.SimpleDateFormat
  profiles:
    active: dev
server:
  port: 8080

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    com.haidong.SeirMeng.service.edu.controller.TeacherController: debug
    root: info

signature:
  appId: y02xMJ1c
  accessKeyId: taRGPE8dPuJT
  keySecret: O3DvH6R7kv3Jamsrs5kk2L34zNqc6zyw

guarantee:
  http:
    addproduct:
      baseUrl: http://testinsure.zxzk.cn/api/anhui_credit_investigation/insurance/add_product
    apply:
      baseUrl: http://testinsure.zxzk.cn/api/anhui_credit_investigation/insurance/apply



